### ISSUE TITLE
Automatic calculation of difference in multiple operations 

### ISSUE THREAD

**Issue by dziennikarka** [akashihi/mdg#2]
In case of multiple operation, software could calculate the amount of unbalanced transaction, e. g. 15 € paid from bank account - 5 €/food + 10/stuff for home. If insert -15 Bank +5 Food, software could inform that transaction is unbalanced and the difference +10.

**Comment by akashihi** [comment]
Fixed with https://github.com/akashihi/mdg-web-ui/commit/c9970eb2a014d4659e2040df921988547246fe0f
